//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public System.DateTime emissionDate { get; set; }
        public int idUser { get; set; }
        public int idTable { get; set; }
        public int idType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Table Table { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual User User { get; set; }
    }
}
